VD-29 l.pak Страница профиля (универсальная)
frontend-park-mail-ru/2022_2_VDonate pull request #1
Opened 2022-09-28 11:57 UTC by MrLeonardPak

2022-09-28 11:58 UTC, MrLeonardPak commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница профиля (универсальная)](https://trello.com/c/zXyqyrS6/29-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8F-%D1%83%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F)

2022-09-29 17:26 UTC, somebody-kseny requested changes
Это что я смогла заметить при не самой внимательной проверке.
Вцелом все неплохо.
Вам нужно, зная сроки, расставить приоритеты и что-то исправить, на что-то забить. К следующим РК хотелось бы видеть все эти комменты поправленными.

Обязательно сделать скрипт сборки и дописать readme, на уровне чтобы бекендер по readme мог собрать и увидеть проект

2022-09-29 17:26 UTC, somebody-kseny commented on .gitignore
> +node_modules
пустая строка в конце файла 👀

public/ сюда однозначно, ну ты уже понял

можно расшить чем-нибудь дефолтным, что могут использовать IDE-шки и ОС

вообще совет внимательно следить, чтобы не залить в гит лишнего

2022-09-29 17:26 UTC, somebody-kseny commented on package.json
> +  },
Сюда скрипты.
Когда настроите линтер, запуск его тоже сюда

2022-09-29 17:26 UTC, somebody-kseny commented on public/index.html
> +  <script id="entry-template" type="text/x-handlebars-template">
шаблон пожалуйста в отдельный файл, и здесь только подключать

2022-09-29 17:26 UTC, somebody-kseny commented on public/index.html
> +        <span class="header__button-link">Лента</span>
за БЭМ большой лайк)

2022-09-29 17:26 UTC, somebody-kseny commented on public/index.js
> +var source = document.getElementById("entry-template").innerHTML;
куда смотрел ментор, который проверял у тебя дз0?))
var устравшее объявление переменной, теперь let и const

var ведет себя немного по-другому, больше неочевидностей допускает, хорошо знать отличия вместе с прочими приколами js, но практически - let и const, чаще const


относится ко всему проекту

2022-09-29 17:26 UTC, somebody-kseny commented on public/index.js
> +const bigText = 'Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста!
вижу const , если var как-то обосновано, сорян, объясни

2022-09-29 17:26 UTC, somebody-kseny commented on public/index.js
> +const bigText = 'Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста!
нетехнический комментарий)
есть вероятность что вы на рк будете показывать с этой заглушкой, повторяющиеся два слова не круто, это привлекает внимание смотрящего
вставь любой текст (lorem ipsum дезигнерам тоже не нравится, есть смешные заглушки в интернете)

2022-09-29 17:26 UTC, somebody-kseny commented on public/index.js
> +document.getElementById("entry").innerHTML += html
ну ругается гитхаб на отсутствие пустой строки)
вдруг на сервере какие-то неожиданные проблемы из-за этого возникнут

2022-09-29 17:26 UTC, somebody-kseny commented on public/index.js
> +      image: "../static/img/4.jpg",
котик это хорошо

2022-09-29 17:26 UTC, somebody-kseny commented on src/style.styl
> +  font-family: 'Circe'
Мне рендерится дефолтный шрифт. Чтобы пользователь видел шрифт, он должен быть либо устаовлен в ОС, либо подключаться в проекте. В системе можно рассчитывать только на самые стандартные 3-5 штук.

Шрифты подключаеются в html аналогично css и script: https://stackoverflow.com/questions/107936/how-to-add-some-non-standard-font-to-a-website
Наиболее простой способ подключать шрифты через google fonts, отдавать со своего сервера по опыту оказывается сложно

имеет смысл задать фолбеки для всех шрифтов, как с Manrope сделал

2022-09-29 17:26 UTC, somebody-kseny commented on src/style.styl
> +    background: bg-second-color
на всех кнопочках `cursor: pointer`, пожалуйста

2022-09-29 17:26 UTC, somebody-kseny commented on src/style.styl
> +    width: 50%
<img width="868" alt="Screen Shot 2022-09-29 at 20 05 25" src="https://user-images.githubusercontent.com/56941752/193094436-154e531f-27ab-4ba9-838a-ee4f8533ccee.png">

2022-09-29 17:26 UTC, somebody-kseny commented on src/style.styl
> +    width: 50%
нужно учесть, что картинки приходят любого размера и соотношения сторон
[вот например как можно сделать](https://code-boxx.com/keep-image-aspect-ratio/#:~:text=CONTROLLED%20IMAGE%20RESIZE) - рекомендую 2А

2022-09-29 17:29 UTC, somebody-kseny commented
Дизайнер во мне не дремлет

1. на мой взгляд если убрать верхний бордер у заголовка, это прям улучшит впечатление от странички 

<img width="626" alt="image" src="https://user-images.githubusercontent.com/56941752/193101401-dd20fa50-5bd1-40dd-ae6f-96b96af0ec10.png">

2. шрифт Times New Roman оставлять нельзя, если подключение красивых попадет под "забить", выставьте хотя бы без засечек

2022-09-29 18:12 UTC, MrLeonardPak commented on public/index.js
> +var source = document.getElementById("entry-template").innerHTML;
Ой, ой. Видимо это остался копипаст с документации handlebars)

2022-09-30 08:39 UTC, SergTyapkin commented on .gitignore
> +public
Ну, строго говоря, тут ещё должны быть `*.css`, потому что они генерятся stylus'ом

2022-09-30 08:39 UTC, SergTyapkin commented on src/index.html
> +            <span class="block__text_type_sub">{{priceDescribtion}}</span>
descriPtion пишется :)

2022-09-30 08:39 UTC, SergTyapkin commented on src/index.js
> +
;

Она забыта во многих местах. Линтер решит проблему сам, когда вы его добавите

2022-09-30 08:39 UTC, SergTyapkin commented on src/index.js
> +  describtion: {
Я прям не могу - descriBtion очень глаза режет)

2022-09-30 08:39 UTC, SergTyapkin commented on src/style.styl
> +bg-main-color = white
Текстовые названия цветов обычно, всё-таки, не пишут. Заменяют на hex-код

2022-09-30 08:39 UTC, SergTyapkin commented on src/style.styl
> +
Константы надо будет потом вынести в constants.styl и подключать их на каждой странице через require

2022-09-30 08:39 UTC, SergTyapkin commented on src/style.styl
> +  font-family: 'Rogalik'
В stylus двоеточия так же не обязательны, как ; и фигурные скобки)

2022-09-30 08:39 UTC, SergTyapkin commented on src/style.styl
> +  font-family: 'Rogalik'
Так что лучше без них

2022-09-30 08:39 UTC, SergTyapkin commented on src/style.styl
> +    sub-text()
Не к этому файлу, но с телефона не могу оставить коммент к картинкам.

Всё иконки (comment.png, like.png) лучше хранить как .svg файлы. Преимущества svg очевидны. А найти их на Google fonts вообще не составляет труда

2022-09-30 09:43 UTC, MrLeonardPak commented on public/index.js
> +const bigText = 'Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста!
var тут случайно

2022-09-30 10:08 UTC, MrLeonardPak commented on public/index.js
> +const bigText = 'Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста! Много текста!
Смешные что то я не нашел)

2022-09-30 10:18 UTC, MrLeonardPak commented on .gitignore
> +public
Я так понял, что они генертся стайлусом в папку паблик. Или нет?

2022-09-30 18:44 UTC, MrLeonardPak commented on src/style.styl
> +  font-family: 'Circe'
Так как гугл не имел те шрифты, которые были, то я взял другую пару. И добавил импорт в css, а не линк в html

2022-09-30 19:24 UTC, MrLeonardPak commented on src/style.styl
> +  font-family: 'Rogalik'
Фигурные скобки нудны, чтобы обозначить функции. ; убрал. Но вот без : читаемость сильно падает, поэтому я оставил их пока

2022-09-30 20:43 UTC, MrLeonardPak commented on src/style.styl
> +    width: 50%
Я пытался не привязывать размер изображения к пикселям, но по другому у меня не вышло

2022-09-30 20:43 UTC, MrLeonardPak commented on src/style.styl
> +    width: 50%
Я немного поправил это но всё равно, как мне кажется, так не подойдет

2022-10-01 14:16 UTC, merged