Vd 21 i.gapoyan - класс Router , API связи с сервером
frontend-park-mail-ru/2022_2_VDonate pull request #3
Opened 2022-10-02 17:38 UTC by Loen15

2022-10-03 18:52 UTC, SergTyapkin requested changes

2022-10-03 18:52 UTC, SergTyapkin commented on src/index.js
> + * @const {*} api класс интерфейса для связи с сервером
Тип у него `Api`

2022-10-03 18:52 UTC, SergTyapkin commented on src/index.js
> + * @const {*} router класс маршрутизации по страницам сайта
тут `Router`, стало быть

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/ajax.js
> + * Модуль, связывающийся с сервером
Лучше "для отправки запросов на сервер через REST API".
Потому что "связь" с сервером по разным протоколам может быть, и по семантике слово "связь" скорее с WebSocket'ами связано

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/ajax.js
> +     * @param {string} baseUrl baseUrl - адрес сайта
не "адрес сайта", а "базовый адрес для обращения на API"

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/ajax.js
> +     * @returns {Object} объект респонса с полями ок, статус и тело
объект ответа. Ну по-русски же пишем :)

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/ajax.js
> +     * @returns {Object} объект респонса с полями ок, статус и тело
Так и перечисли эти поля в нормальном виде. Внутри скобочек фигурных

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/ajax.js
> +     * создает POST запрос, возвращает  объект респонса с полями ок, статус и тело
запросы отправляются, а не создаются :)

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/ajax.js
> +     * @param {Object} data данные для query-параметров
Уже не query-параметры, а тело запроса. Query были в GET запросах, потому что с ними нельзя отправлять тело

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/ajax.js
> +     * формирует Request, возвращает Response
Тут не понятно, что именно здесь отправляется запрос на заданный url.
И возвращается не Response, а промис

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/ajax.js
> +                'Content-Type': 'aplication/json',
a`pp`lication/json

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/ajax.js
> +     * конвертирует Response в объект с полями ок, статус и тело
пропиши тут тоже поля нормально, как пример объекта

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/api.js
> +     */
Вот честно говоря, не уверен я, что тут действительно нужно писать JSDoc к каждому этому маленькому методу.

Они отлично умещаются в одну строчку, и изначально созданы именно для того, чтобы хорошо читаться и не занимать много места. А тут, получается, ты сделал абсолютно обратное. Да и вообще, если можешь в каком-либо месте обосновать, почему JSDoc не нужен - то лучше его не делать)

@somebody-kseny , с удовольствием выслушаю твои мысли на этот счет

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/api.js
> +}
перенос в конце файла :)

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/router.js
> +     * @param {Element} root корень HTML файла, куда будет рендериться страница
Я не смог понять, что такое "корень HTML файла".
Давай перефразируем

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/router.js
> +                console.log(target);
итоговая версия на рк без таких вот дебажных логов должна быть. Сейчас ок

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/router.js
> +                route.render(this);
Уверен, что нужно перерендеривать текущую страницу, если её нет в роутах, а не просто ничего не делать?

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/router.js
> +        })
;

2022-10-03 18:52 UTC, SergTyapkin commented on src/modules/router.js
> +        this.goTo('/profile?id=1');
Почему на `?id=1`?

2022-10-03 18:52 UTC, SergTyapkin commented on src/views/404.js
> +}
Со страницы 404 хорошо бы ссылку на главную где-то выдать. А то с неё уйти, получается, невозможно никуда

2022-10-03 18:52 UTC, SergTyapkin commented on src/views/profile.js
> +  let author = {
const

2022-10-03 18:52 UTC, SergTyapkin commented on src/views/profile.js
> +  let donater = {
const

2022-10-04 15:34 UTC, Loen15 commented on src/modules/router.js
> +                route.render(this);
Так я и рендерю страницы если они есть в роутах, а если ее в роутах нет, то я ничего не делаю

2022-10-04 15:37 UTC, Loen15 commented on src/modules/router.js
> +        this.goTo('/profile?id=1');
это временная строка для того чтобы отправить запрос для проверки

2022-10-04 19:17 UTC, merged