VD 31 l.pak
frontend-park-mail-ru/2022_2_VDonate pull request #5
Opened 2022-10-03 07:48 UTC by MrLeonardPak

+ Валидация форм
+ Немного изменена верстка форм

2022-10-03 19:10 UTC, SergTyapkin requested changes
Всё хорошо, только надо избавиться от работы со стилями из JS, и работать только с классами

2022-10-03 19:10 UTC, SergTyapkin commented on src/module/validationForm.js
> +    email.style = '';
Можно оформить эти функции как function, и написать JSDoc, потому что вот сейчас вообще не понятно, чем должна являться переменная `email`.

(ну то есть понятно, что `Element`, но не очевидно)

2022-10-03 19:10 UTC, SergTyapkin commented on src/module/validationForm.js
> +  email.style.borderColor = 'red';
Работать с inline-стилями из JS - очень плохая практика. Вместо этого работай с классами. Здесь можно класс `error` добавлять или убирать, например

2022-10-03 19:10 UTC, SergTyapkin commented on src/module/validationForm.js
> +  if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(email.value)) {
А почему у тебя почта обязана кончатся на `\w{2,3}`?

Это может быть такой же адрес сайта, и имя доменной зоны для него не обязано быть .ru или .com. 
Из самых популярных могу вспомнить .info и .live, например. В общем там сколько угодно символов может быть, хоть .leonard :)

2022-10-03 19:10 UTC, SergTyapkin commented on src/module/validationForm.js
> +  if (username.value !== '') {
Нужна проверка на то, что имя состоит из допустимых символов, плюс проверка на макс. и мин. длину

2022-10-03 19:10 UTC, SergTyapkin commented on src/module/validationForm.js
> +  if (/^[\S]+$/.test(password.value)) {
Тоже проверка на длину.

А проверка на допустимые символы никогда не делается через черный список (исключением каких-то символов), как ты сделал.

Нужно через белый список сделать, то есть перечислить именно допустимые символы

2022-10-03 19:10 UTC, SergTyapkin commented on src/style.styl
> +    padding 40px;
; лишние

2022-10-03 19:10 UTC, SergTyapkin commented on src/style.styl
>  @import url('https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&family=Noto+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;
Делать ссылки на сторонние ресурсы где бы то ни было на сайте - плохая практика. Ведь если там они изменят или удалят этот файл (в данном случае, шрифта), то у тебя на сайте тоже всё поедет. В идеале надо скачивать и раздавать как статику, с вашего же сервера.

Но это на будущее - потом исправите

2022-10-03 19:13 UTC, SergTyapkin commented on src/module/validationForm.js
> +  if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(email.value)) {
И вообще сейчас буду душнить, но ты разрешаешь только спецсимволы `.` и `-`.

А вот что на самом деле можно использовать в адресе email: https://en.wikipedia.org/wiki/Email_address#Local-part

2022-10-04 09:38 UTC, MrLeonardPak commented on src/module/validationForm.js
> +  if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(email.value)) {
Изменил проверку, но не все символы получается проверять в локальной части. Тут оказываются допустимые символы. Если я добавлю хоть один ещё  символ, то regexp начинает пускать несколько `.` подряд. Так и не понял в чем дело
```javascript
const localSyms = /[a-zA-Z0-9!#\$&%_+-]/;
```

2022-10-04 19:08 UTC, merged