VD 38 l.pak
frontend-park-mail-ru/2022_2_VDonate pull request #8
Opened 2022-10-05 10:36 UTC by MrLeonardPak

- обработка fetch запросов в async
- обработка статус кода после запросов
- фикс jsdoc

2022-10-05 20:02 UTC, SergTyapkin requested changes
До РК по фронту нужно всё это поправить. + **комменты в телеге** (они, как раз, более важные, чем комментарии в этом ПР)

2022-10-05 20:02 UTC, SergTyapkin commented on src/modules/router.js
>          window.history.pushState(null, null, loc);
`pushState` надо вызывать до рендера `page404`, потому что отрисовывается новая страница и пользователь хочет ткнуть кнопку "назад", чтобы вернуться. 
Нетрудно понять, что возвращается он в очень неожиданное место

2022-10-05 20:02 UTC, SergTyapkin commented on src/modules/ajax.js
> +        const jsonBody = response.ok ? await response.json() : {};
`await response.json()` нужно обернуть в `try {..} catch {...}`. Потому что прийти с сервера может всё что угодно, да хоть HTML вместо того, что ты ожидаешь. И тогда у тебя что-нибудь где-нибудь обязательно отъедет)

2022-10-05 20:02 UTC, SergTyapkin commented on src/modules/router.js
>                  if (route != undefined) {
==========================================================
Надо строгое равенство
========================================================
Очень строгое !

2022-10-05 20:02 UTC, SergTyapkin commented on src/modules/router.js
>          this._api = value;
Зачем нужны геттеры и сеттеры на эти свойства, если они выполняют стандартные действия?

Почему вместо этого не просто убрать нижние подчеркивания у свойств?

2022-10-05 20:02 UTC, SergTyapkin commented on src/index.js
>  window.processForm = processForm;
_Комментарий про шаблоны с картинкой в телеге_

2022-10-05 20:02 UTC, SergTyapkin commented on src/views/login.js
>      },
_Комментарий про шаблоны с картинкой в телеге_

2022-10-05 20:02 UTC, SergTyapkin commented on src/modules/validationForm.js
> + * @param {int} status код ответа
А типа `int` в JS нет :)
Только `number` :(

2022-10-05 20:02 UTC, SergTyapkin commented on src/style.styl
>    &__image
_Комментарий про стили, вёрстку и скроллы с картинками в телеге_

2022-10-06 09:07 UTC, leonard-pak commented on src/modules/ajax.js
> +        const jsonBody = response.ok ? await response.json() : {};
Добавил просто catch для промиса. Код 515 пока поставил сам (типа 415, только для сервера)

2022-10-09 22:06 UTC, merged